export const SEARCH_GET_TRACKS = 'SEARCH_GET_TRACKS';
export const SEARCH_GET_ARTISTS = 'SEARCH_GET_ARTISTS';
export const SEARCH_GET_ALBUMS = 'SEARCH_GET_ALBUMS';

export const GET_TRACKS = 'GET_TRACKS';
export const GET_ARTISTS = 'GET_ARTISTS';
export const GET_ALBUMS = 'GET_ALBUMS';

export const GET_ARTIST_TRACKS = 'GET_ARTIST_TRACKS';
export const GET_ARTIST_ALBUMS = 'GET_ARTIST_ALBUMS';
export const GET_ARTIST_INFO = 'GET_ARTIST_INFO';

export const FETCH_ALBUM = 'FETCH_ALBUM';

export const SET_TRACK = 'SET_TRACK';
