export const SEARCH_GET_TRACKS = 'SEARCH_GET_TRACKS';
export const SEARCH_GET_ARTISTS = 'SEARCH_GET_ARTISTS';

export const GET_TRACKS = 'GET_TRACKS';
export const GET_ARTISTS = 'GET_ARTISTS';
export const GET_ALBUMS = 'GET_ALBUMS';

export const GET_ARTIST_TRACKS = 'GET_ARTIST_TRACKS';
